
name = input("Shierlene Lasic")
print(name)
address = input("Torrijos,Marinduque")
print(address)
birthday = input("September 29")
print(birthday)

college = input ("Marinduque State College")
print(college)
course = input ("BS Information Technology")
print(course)
year = input ("3rd year")
print(year)
section = input ("Section B")
print(section)